fix: gitlab ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -45,92 +45,91 @@ deploy-staging:
     - dpkg -i "session-manager-plugin.deb"
     - apt-get install -y session-manager-plugin
     - apt-get install -y expect
-    - unbuffer aws ssm start-session --target "i-06f240a3b2e573928" --document-name "AWS-StartSSHSession" --parameters '{"Commands":["sudo sh -c \"docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d"]}'
+    # - unbuffer aws ssm start-session --target "i-06f240a3b2e573928" --document-name "AWS-StartSSHSession" --parameters '{"Commands":["sudo sh -c \"docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d"]}'
     
     # - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login --username "$CONTAINER_REGISTRY_USERNAME" --password-stdin "$CONTAINER_REGISTRY_URL"
     # - pwd  # Print the current working directory
     # - wget -O docker-compose.yml "$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/docker-compose.yml"
     # - docker-compose -f docker-compose.yml pull
     # - docker-compose -f docker-compose.yml up -d
-    # - >
-    #   DOCUMENT_NAME="AppDockerComposeDeploy_$(date +'%Y%m%d%H%M%S')"
-    #   COMMAND_ID=$(aws ssm create-document \
-    #     --name "$DOCUMENT_NAME" \
-    #     --document-type "Command" \
-    #     --document-format "YAML" \
-    #     --content "\
-    #     {
-    #       \"schemaVersion\":\"2.2\",
-    #       \"description\":\"Docker Compose Deploy\",
-    #       \"mainSteps\":[
-    #         {
-    #           \"action\":\"aws:runShellScript\",
-    #           \"name\":\"runShellScript\",
-    #           \"inputs\":{
-    #             \"runCommand\":[
-    #               # \"cd /data/app\",
-    #               \"ls -la \",
-    #               \"pwd\",
-    #               \"docker stop backend && docker rm backend\",
-    #               \"curl -o docker-compose.yml '$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/docker-compose.yml' \",
-    #               \"docker-compose pull docker-compose.yml \",
-    #               \"docker-compose up -d \",
-    #               # \"docker image prune -af\"
-    #             ]
-    #           }
-    #         }
-    #       ]
-    #     }")
+    - >
+      DOCUMENT_NAME="AppDockerComposeDeploy_$(date +'%Y%m%d%H%M%S')"
+      COMMAND_ID=$(aws ssm create-document \
+        --name "$DOCUMENT_NAME" \
+        --document-type "Command" \
+        --document-format "YAML" \
+        --content "\
+        {
+          \"schemaVersion\":\"2.2\",
+          \"description\":\"Docker Compose Deploy\",
+          \"mainSteps\":[
+            {
+              \"action\":\"aws:runShellScript\",
+              \"name\":\"runShellScript\",
+              \"inputs\":{
+                \"runCommand\":[
+                  # \"cd /data/app\",
+                  \"ls -la \",
+                  \"pwd\",
+                  \"docker stop backend && docker rm backend\",
+                  \"docker-compose pull -f docker-compose.yml \",
+                  \"docker-compose up -d \",
+                  # \"docker image prune -af\"
+                ]
+              }
+            }
+          ]
+        }")
 
-    # - >
-    #   EXECUTION_ID=$(aws ssm send-command \
-    #     --document-name "$DOCUMENT_NAME" \
-    #     --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"i-06f240a3b2e573928\"]}]" \
-    #     --output text \
-    #     --query "Command.CommandId")
+    - >
+      EXECUTION_ID=$(aws ssm send-command \
+        --document-name "$DOCUMENT_NAME" \
+        --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"i-06f240a3b2e573928\"]}]" \
+        --output text \
+        --query "Command.CommandId")
 
-    # # Implement a retry mechanism with exponential backoff
-    # - MAX_RETRIES=10
-    # - RETRY_INTERVAL=10  # Initial retry interval in seconds
+    # Implement a retry mechanism with exponential backoff
+    - MAX_RETRIES=10
+    - RETRY_INTERVAL=10  # Initial retry interval in seconds
 
-    # - >
-    #   retry() {
-    #     if [ "$MAX_RETRIES" -eq 0 ]; then
-    #       echo "Docker Compose deployment to staging failed after $MAX_RETRIES attempts."
-    #       exit 1
-    #     fi
+    - >
+      retry() {
+        if [ "$MAX_RETRIES" -eq 0 ]; then
+          echo "Docker Compose deployment to staging failed after $MAX_RETRIES attempts."
+          exit 1
+        fi
 
-    #     EXECUTION_STATUS=$(aws ssm get-command-invocation \
-    #       --instance-id "i-06f240a3b2e573928" \
-    #       --command-id "$EXECUTION_ID" \
-    #       --query "Status" \
-    #       --output text)
+        EXECUTION_STATUS=$(aws ssm get-command-invocation \
+          --instance-id "i-06f240a3b2e573928" \
+          --command-id "$EXECUTION_ID" \
+          --query "Status" \
+          --output text)
         
-    #     echo "Current execution status: $EXECUTION_STATUS"
+        echo "Current execution status: $EXECUTION_STATUS"
 
-    #     if [ "$EXECUTION_STATUS" = "Success" ]; then
-    #       echo "Docker Compose deployment to staging successful."
-    #     elif [ "$EXECUTION_STATUS" = "InProgress" ]; then
-    #       echo "Deployment is still in progress. Retrying in $RETRY_INTERVAL seconds..."
-    #       sleep "$RETRY_INTERVAL"
-    #       RETRY_INTERVAL=$(expr "$RETRY_INTERVAL" \* 2)  # Exponential backoff
-    #       MAX_RETRIES=$(expr "$MAX_RETRIES" - 1)
-    #       retry
-    #     elif [ "$EXECUTION_STATUS" = "Failed" ]; then
-    #       ERROR_INFO=$(aws ssm get-command-invocation \
-    #         --instance-id "i-06f240a3b2e573928" \
-    #         --command-id "$EXECUTION_ID" \
-    #         --output text)
-    #       echo "Error details: $ERROR_INFO"
-    #       echo "Deployment failed with status: $EXECUTION_STATUS"
-    #       exit 1
-    #     fi
-    #   }
-    #   # Call the retry function
-    # - echo "Calling the retry function..."
-    # - echo "Document Name - $DOCUMENT_NAME"
-    # - echo "Execution ID -  $EXECUTION_ID"
-    # - retry
+        if [ "$EXECUTION_STATUS" = "Success" ]; then
+          echo "Docker Compose deployment to staging successful."
+        elif [ "$EXECUTION_STATUS" = "InProgress" ]; then
+          echo "Deployment is still in progress. Retrying in $RETRY_INTERVAL seconds..."
+          sleep "$RETRY_INTERVAL"
+          RETRY_INTERVAL=$(expr "$RETRY_INTERVAL" \* 2)  # Exponential backoff
+          MAX_RETRIES=$(expr "$MAX_RETRIES" - 1)
+          retry
+        elif [ "$EXECUTION_STATUS" = "Failed" ]; then
+          ERROR_INFO=$(aws ssm get-command-invocation \
+            --instance-id "i-06f240a3b2e573928" \
+            --command-id "$EXECUTION_ID" \
+            --output text)
+          echo "Error details: $ERROR_INFO"
+          echo "Deployment failed with status: $EXECUTION_STATUS"
+          exit 1
+        fi
+      }
+      # Call the retry function
+    - echo "Calling the retry function..."
+    - echo "Document Name - $DOCUMENT_NAME"
+    - echo "Execution ID -  $EXECUTION_ID"
+    - retry
 
   only:
     - staging
