Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,55 +3,95 @@ stages:
   - deploy-staging
   - deploy-production
 
+variables:
+  DOCKER_DRIVER: overlay2
+
+before_script:
+  - apk add --no-cache git
+  - apk add --update --no-cache aws-cli
+  - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login --username "$CONTAINER_REGISTRY_USERNAME" --password-stdin "$CONTAINER_REGISTRY_URL"
+
 build:
   stage: build
   image: docker:latest
   services:
     - docker:dind
-  before_script:
-    - apk add --no-cache git
   script:
-    - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login --username "$CONTAINER_REGISTRY_USERNAME" --password-stdin "$CONTAINER_REGISTRY_URL"
     - docker build -t $CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG .
     - docker tag $CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG $CONTAINER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG
     - docker push $CONTAINER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG
+  only:
+    - branches  # Specify the branches where this stage should run
 
-staging:
+deploy-staging:
   stage: deploy-staging
-  image: docker:latest
-  services:
-    - docker:dind
-  before_script:
-    - apk add --update --no-cache aws-cli
   script:
     - aws configure set aws_access_key_id $ACCESS_KEY_ID
     - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
     - aws configure set region $AWS_DEFAULT_REGION
-    - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login --username "$CONTAINER_REGISTRY_USERNAME" --password-stdin "$CONTAINER_REGISTRY_URL"
     - docker pull "$CONTAINER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG"
-
-    # Send the Docker Compose commands via AWS SSM Run Command
-    # Run the AWS SSM Run Command and capture the Command ID
     - >
-      COMMAND_ID=$(aws ssm send-command \
-        --instance-ids "i-06f240a3b2e573928" \
-        --document-name "AWS-RunShellScript" \
-        --comment "Deploying chats api" \
-        --parameters commands="docker" \
+      COMMAND_ID=$(aws ssm create-document \
+        --name "DockerComposeDeploy" \
+        --document-type "Command" \
+        --document-format "yaml" \
+        --content "{\"schemaVersion\":\"2.2\",\"description\":\"Docker Compose Deploy\",\"mainSteps\":[{\"action\":\"aws:runShellScript\",\"name\":\"runShellScript\",\"inputs\":{\"runCommand\":[\"docker-compose -f docker-compose.prod.yml up -d\"]}}]}")
+    - >
+      EXECUTION_ID=$(aws ssm create-association \
+        --name "DockerComposeDeploy" \
+        --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"i-06f240a3b2e573928\"]}]" \
+        --association-name "DockerComposeDeploy" \
+        --document-version "\$LATEST" \
         --output text \
-        --query "Command.CommandId")
-
-        # Wait for a few seconds to allow the command to be executed
-        sleep 5
-
-        # aws ssm list-command-invocations \
-        #   --instance-id "i-06f240a3b2e573928" \
-        #   --query "CommandInvocations[].Status" \
-          
-        aws ssm get-command-invocation \
-          --instance-id "i-06f240a3b2e573928" \
-          --command-id "$COMMAND_ID" \
-          --query "StandardOutputContent" \
-
+        --query "AssociationDescription.AssociationId")
+    - >
+      EXECUTION_STATUS=$(aws ssm wait command-executed \
+        --instance-id "i-06f240a3b2e573928" \
+        --command-id "$EXECUTION_ID" \
+        --query "Status")
+    - >
+      if [ "$EXECUTION_STATUS" == "Success" ]; then
+        echo "Docker Compose deployment to staging successful."
+      else
+        echo "Docker Compose deployment to staging failed."
+        exit 1
+      fi
   only:
     - staging
+
+deploy-production:
+  stage: deploy-production
+  script:
+    - aws configure set aws_access_key_id $ACCESS_KEY_ID
+    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+    - aws configure set region $AWS_DEFAULT_REGION
+    - docker pull "$CONTAINER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG"
+    - >
+      COMMAND_ID=$(aws ssm create-document \
+        --name "DockerComposeDeploy" \
+        --document-type "Command" \
+        --document-format "yaml" \
+        --content "{\"schemaVersion\":\"2.2\",\"description\":\"Docker Compose Deploy\",\"mainSteps\":[{\"action\":\"aws:runShellScript\",\"name\":\"runShellScript\",\"inputs\":{\"runCommand\":[\"docker-compose -f docker-compose.prod.yml up -d\"]}}]}")
+    - >
+      EXECUTION_ID=$(aws ssm create-association \
+        --name "DockerComposeDeploy" \
+        --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"i-xxxxxxxxxxxxxxxxx\"]}]" \
+        --association-name "DockerComposeDeploy" \
+        --document-version "\$LATEST" \
+        --output text \
+        --query "AssociationDescription.AssociationId")
+    - >
+      EXECUTION_STATUS=$(aws ssm wait command-executed \
+        --instance-id "i-xxxxxxxxxxxxxxxxx" \
+        --command-id "$EXECUTION_ID" \
+        --query "Status")
+    - >
+      if [ "$EXECUTION_STATUS" == "Success" ]; then
+        echo "Docker Compose deployment to production successful."
+      else
+        echo "Docker Compose deployment to production failed."
+        exit 1
+      fi
+  only:
+    - production
+
