Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -53,8 +53,12 @@ deploy-staging:
     - MAX_RETRIES=10
     - RETRY_INTERVAL=10  # Initial retry interval in seconds
     - >
-      i=1
-      for i in $(seq "$MAX_RETRIES"); do
+      retry() {
+        if [ "$MAX_RETRIES" -eq 0 ]; then
+          echo "Docker Compose deployment to staging failed after $MAX_RETRIES attempts."
+          exit 1
+        fi
+
         EXECUTION_STATUS=$(aws ssm describe-command-invocation \
           --instance-id "i-06f240a3b2e573928" \
           --command-id "$EXECUTION_ID" \
@@ -63,17 +67,17 @@ deploy-staging:
 
         if [ "$EXECUTION_STATUS" = "Success" ]; then
           echo "Docker Compose deployment to staging successful."
-          break
-        elif [ "$i" -eq "$MAX_RETRIES" ]; then
-          echo "Docker Compose deployment to staging failed after $MAX_RETRIES attempts."
-          exit 1
         else
           echo "Retrying in $RETRY_INTERVAL seconds..."
           sleep "$RETRY_INTERVAL"
           RETRY_INTERVAL=$(expr "$RETRY_INTERVAL" \* 2)  # Exponential backoff
-          i=$(expr "$i" + 1)
+          MAX_RETRIES=$(expr "$MAX_RETRIES" - 1)
+          retry
         fi
-      done
+      }
+
+      # Call the retry function
+      retry
   only:
     - staging
 
