Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -47,18 +47,30 @@ deploy-staging:
         --document-version "\$LATEST" \
         --output text \
         --query "AssociationDescription.AssociationId")
+
+    # Implement a retry mechanism with exponential backoff
+    - MAX_RETRIES=10
+    - RETRY_INTERVAL=10  # Initial retry interval in seconds
     - >
-      EXECUTION_STATUS=$(aws ssm wait command-executed \
-        --instance-id "i-06f240a3b2e573928" \
-        --command-id "$EXECUTION_ID" \
-        --query "Status")
-    - >
-      if [ "$EXECUTION_STATUS" == "Success" ]; then
-        echo "Docker Compose deployment to staging successful."
-      else
-        echo "Docker Compose deployment to staging failed."
-        exit 1
-      fi
+      for ((i=1; i<=MAX_RETRIES; i++)); do
+        EXECUTION_STATUS=$(aws ssm describe-command-invocation \
+          --instance-id "i-06f240a3b2e573928" \
+          --command-id "$EXECUTION_ID" \
+          --query "Status" \
+          --output text)
+
+        if [ "$EXECUTION_STATUS" == "Success" ]; then
+          echo "Docker Compose deployment to staging successful."
+          break
+        elif [ "$i" -eq "$MAX_RETRIES" ]; then
+          echo "Docker Compose deployment to staging failed after $MAX_RETRIES attempts."
+          exit 1
+        else
+          echo "Retrying in $RETRY_INTERVAL seconds..."
+          sleep $RETRY_INTERVAL
+          RETRY_INTERVAL=$((RETRY_INTERVAL * 2))  # Exponential backoff
+        fi
+      done
   only:
     - staging
 
